name: Update VCPKG Registry

on:
  repository_dispatch:
    types: [update-event]
  workflow_dispatch:

env:
  VCPKG_COMMIT_ID: 424ed5e6737117a53b947c5a8c09bc2860cd5469
  VCPKG_PORT_REPO: ${{ github.repository_owner }}

jobs:
  update-registry:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.VCPKG_HELPER_TOKEN }}

      - name: Setup VCPKG
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Update Registry
        id: registry
        shell: pwsh
        run: "& ${{ github.workspace }}/.github/update-registry.ps1 ${{ github.event.client_payload.sha }}"

      - name: Check for Commit
        if: ${{ steps.registry.outputs.VCPKG_SUCCESS }} == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: vcpkg-action
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: update registry"
